# Generated by Django 5.1.4 on 2024-12-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(default='lnadm73-FE', max_length=10, unique=True)),
                ('health', models.IntegerField(default=100)),
                ('items', models.JSONField(default=list)),
                ('current_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adventure.location')),
            ],
        ),
    ]
