# Generated by Django 5.1.4 on 2024-12-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_location_image_alter_playerstatus_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='health_modify',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerstatus',
            name='player_id',
            field=models.CharField(default='YExdp2Red9', max_length=10, unique=True),
        ),
    ]
