# Generated by Django 5.1.4 on 2024-12-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_choice_health_modify_alter_playerstatus_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='fight_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerstatus',
            name='player_id',
            field=models.CharField(default='-_rH4L14IE', max_length=10, unique=True),
        ),
    ]
